import { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import { C, F } from '../constants';

const UPDATED = 'April 24, 2026';

// ─── Content ─────────────────────────────────────────────────────
const privacy = [
  {
    id: 'pp-intro', n: '01', title: 'Introduction',
    body: `Boardwalk Labs LLC ("Boardwalk Labs," "we," "us," or "our") operates Octopilot AI and provides custom software development services to educational institutions, businesses, and individual clients. This Privacy Policy explains how we collect, use, disclose, and protect personal information across all of our products and services.

By using any Boardwalk Labs product or engaging us for a software contract, you agree to the practices described in this policy. If you do not agree, please discontinue use of our services.

This policy applies to all users of Octopilot AI, visitors to our website at boardwalklabs.co, and clients who engage us for custom software engagements.`,
  },
  {
    id: 'pp-collect', n: '02', title: 'Information We Collect',
    body: `We collect information you provide directly and information generated by your use of our services.

**Account & Identity Information**
Name, email address, institutional or organizational affiliation, job title, and billing information when you create an account or initiate a contract engagement.

**Content Data**
Documents, drafts, source materials, briefs, and other content you submit to Octopilot AI for processing. For custom software clients, this may include business requirements, data schemas, and proprietary specifications shared during the engagement.

**Usage & Interaction Data**
Features accessed, session duration, actions taken within the product, error logs, and performance metrics. This data helps us improve the product and diagnose issues.

**Communications**
Emails, messages, and other correspondence you send us — including project inquiries, support requests, and contract communications.

**Technical Data**
IP address, browser type and version, operating system, device identifiers, and referring URLs. Collected automatically via standard web server logs and cookies.`,
  },
  {
    id: 'pp-use', n: '03', title: 'How We Use Your Information',
    body: `**To Deliver Our Services**
We use your information to operate Octopilot AI, fulfill custom software contracts, process payments, and provide customer support.

**To Improve Our Products**
Aggregated and anonymized usage data informs product decisions, feature prioritization, and performance optimization. We do not use individual user content to train AI models without explicit, separate consent.

**To Communicate with You**
We send transactional emails (account activity, invoices, contract milestones), product updates, and — only with your consent — marketing communications. You may opt out of marketing emails at any time.

**To Ensure Security**
We monitor for fraudulent activity, unauthorized access, and abuse of our services. Security logs may be retained even after account deletion.

**To Comply with Legal Obligations**
We may process your data to comply with applicable law, respond to legal process, or protect our legal rights.`,
  },
  {
    id: 'pp-student', n: '04', title: 'Student Data & FERPA',
    body: `Boardwalk Labs takes student privacy seriously. When Octopilot AI is deployed by an educational institution, student data submitted through the platform may constitute "education records" under the Family Educational Rights and Privacy Act (FERPA).

**Our Commitments Under FERPA**
We act as a "school official" with a "legitimate educational interest" as defined by FERPA only to the extent necessary to provide the contracted service. We do not disclose student education records to third parties without prior consent from the institution, except as required by law.

**We Do Not Sell Student Data**
We will never sell, rent, trade, or otherwise disclose student personal information for advertising, marketing, or any commercial purpose unrelated to providing the service.

**Data Minimization**
We collect only the student data required to deliver the product. Institutions retain control over what data is submitted to the platform.

**COPPA — Children Under 13**
Octopilot AI is not designed for or directed to children under the age of 13. We do not knowingly collect personal information from children under 13. If we discover we have inadvertently collected such information, we will delete it promptly. Institutions deploying our products are responsible for ensuring age-appropriate access controls.`,
  },
  {
    id: 'pp-sharing', n: '05', title: 'Data Sharing & Disclosure',
    body: `**We Do Not Sell Your Data.** Full stop.

**Service Providers**
We engage trusted third-party vendors to operate our infrastructure — including cloud hosting (AWS), payment processing (Stripe), and error monitoring (Sentry). These vendors are contractually bound to process data only on our behalf and in accordance with this policy.

**Custom Software Clients**
In the course of a contract engagement, client-provided data (requirements, specifications, test data) is handled by the assigned project team only. We do not share client confidential information with other clients or third parties.

**Legal Requirements**
We may disclose information if required by law, subpoena, court order, or government authority, or if we believe disclosure is necessary to protect our rights, your safety, or the safety of others.

**Business Transfers**
In the event of a merger, acquisition, or sale of substantially all of our assets, your information may be transferred as part of that transaction. We will notify you before your data is subject to a materially different privacy policy.`,
  },
  {
    id: 'pp-security', n: '06', title: 'Security',
    body: `We implement industry-standard technical and organizational measures to protect your personal information.

**Encryption**
All data transmitted between your device and our servers is encrypted using TLS 1.2 or higher. Data stored in our systems is encrypted at rest using AES-256.

**Access Controls**
Access to personal data is restricted to team members who need it to perform their job functions. All team members are subject to confidentiality obligations.

**Breach Notification**
In the event of a data breach that affects your personal information, we will notify affected users within 72 hours of becoming aware of the breach, and will comply with all applicable breach notification laws.

**Limitations**
No system is perfectly secure. We encourage you to use strong, unique passwords and to contact us immediately at support@octopilotai.com if you suspect unauthorized access to your account.`,
  },
  {
    id: 'pp-retention', n: '07', title: 'Data Retention',
    body: `**Active Accounts**
We retain your personal information for as long as your account is active or as needed to provide services.

**Account Deletion**
When you delete your account, we will delete or anonymize your personal information within 30 days, except where retention is required by law, to resolve disputes, or to enforce our agreements.

**Custom Software Engagements**
Project data, communications, and deliverable documentation are retained for a minimum of 7 years following contract completion, as required for standard business record-keeping and potential legal proceedings.

**Content Data**
Documents and content you submit to Octopilot AI are retained only as long as necessary to process and return results, unless you explicitly save them within the platform. We do not retain submitted content for AI training purposes without consent.`,
  },
  {
    id: 'pp-rights', n: '08', title: 'Your Rights',
    body: `Depending on your jurisdiction, you may have the following rights regarding your personal data:

**Access & Portability**
You may request a copy of the personal information we hold about you, in a machine-readable format.

**Correction**
You may request correction of inaccurate or incomplete personal information.

**Deletion**
You may request deletion of your personal information, subject to legal retention requirements.

**Objection & Restriction**
You may object to certain processing of your data or request that we restrict processing in specific circumstances.

**GDPR (European Users)**
If you are located in the European Economic Area, you have additional rights under the General Data Protection Regulation, including the right to lodge a complaint with a supervisory authority.

**CCPA (California Residents)**
California residents have the right to know what personal information we collect, to request deletion, and to opt out of any sale of personal information (we do not sell personal information).

To exercise any of these rights, contact us at support@octopilotai.com. We will respond within 30 days.`,
  },
  {
    id: 'pp-cookies', n: '09', title: 'Cookies',
    body: `We use a minimal set of cookies required to operate our services.

**Essential Cookies**
These are necessary for the platform to function — session management, authentication, and security tokens. You cannot opt out of essential cookies without discontinuing use of the service.

**Analytics Cookies**
We use privacy-respecting analytics to understand how users interact with our product. This data is aggregated and does not identify individual users. You may opt out via your browser settings.

**No Advertising Cookies**
We do not use third-party advertising cookies or tracking pixels. We do not participate in cross-site behavioral advertising networks.`,
  },
  {
    id: 'pp-contact', n: '10', title: 'Contact & Updates',
    body: `**Privacy Questions**
For questions, requests, or concerns about this Privacy Policy or our data practices, contact us at:

Boardwalk Labs LLC
Attn: Privacy
No. 418 Broadway, Suite N
Albany, New York 12207
support@octopilotai.com

**Policy Updates**
We may update this Privacy Policy from time to time. When we make material changes, we will notify you by email or by posting a prominent notice on our website. Your continued use of our services after the effective date of any update constitutes acceptance of the revised policy.

This policy was last updated on ${UPDATED}.`,
  },
];

const terms = [
  {
    id: 'tos-acceptance', n: '01', title: 'Acceptance of Terms',
    body: `By accessing or using any Boardwalk Labs LLC product or service — including Octopilot AI and any custom software developed under a contract with us — you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy.

If you are entering into these Terms on behalf of an organization (a school, university, company, or other entity), you represent that you have the authority to bind that organization to these Terms. If you do not have such authority, or do not agree with these Terms, do not use our services.

We reserve the right to update these Terms at any time. Continued use of our services after updates constitutes acceptance of the revised Terms.`,
  },
  {
    id: 'tos-services', n: '02', title: 'Description of Services',
    body: `Boardwalk Labs LLC provides two categories of services:

**Academic Software Products**
Octopilot AI is an AI-powered writing and research assistant designed for educators, students, writers, and researchers. It helps users draft, revise, and refine written work using artificial intelligence.

**Custom Software Development**
We accept a limited number of custom software engagements per year. These are project-based contracts governed by a separate Statement of Work (SOW) or Master Service Agreement (MSA) in addition to these Terms. In cases of conflict between a SOW/MSA and these Terms, the SOW/MSA takes precedence.

We reserve the right to modify, suspend, or discontinue any product or service at any time with reasonable notice.`,
  },
  {
    id: 'tos-eligibility', n: '03', title: 'Eligibility & Accounts',
    body: `**Eligibility**
You must be at least 13 years of age to use Octopilot AI. Users under 18 must have consent from a parent or guardian, or use the platform through an educational institution that has agreed to these Terms on their behalf.

**Account Registration**
You agree to provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.

**Institutional Accounts**
Schools, universities, and organizations that deploy Octopilot AI for their users are responsible for ensuring that their users comply with these Terms. The institution assumes responsibility for appropriate use within their deployment.`,
  },
  {
    id: 'tos-use', n: '04', title: 'Acceptable Use',
    body: `**Permitted Use**
You may use Boardwalk Labs services for lawful personal, educational, research, and business purposes consistent with these Terms.

**Prohibited Conduct**
You may not use our services to:

— Submit, upload, or process content that is illegal, defamatory, harassing, threatening, or that violates the rights of any third party.
— Attempt to reverse-engineer, decompile, or derive source code from any Boardwalk Labs product.
— Use our services to develop a competing product or service.
— Circumvent, disable, or interfere with security features of the platform.
— Use automated tools, bots, or scrapers to access the service in ways not authorized by us.
— Submit false, misleading, or fraudulent information.

**Academic Integrity**
Octopilot AI is a writing and research tool. Users are solely responsible for ensuring their use of AI-generated content complies with the academic integrity policies of their institution. Boardwalk Labs does not condone plagiarism, academic fraud, or misrepresentation of AI-generated work as original human writing in contexts where that is prohibited.`,
  },
  {
    id: 'tos-ip', n: '05', title: 'Intellectual Property',
    body: `**Your Content**
You retain all ownership rights to content you submit to Octopilot AI. By submitting content, you grant Boardwalk Labs a limited, non-exclusive license to process that content solely for the purpose of delivering the service to you. We do not claim ownership of your content.

**AI-Generated Output**
Output generated by Octopilot AI in response to your prompts is provided to you for your use. We make no warranties about the originality or copyright status of AI-generated text. You are responsible for reviewing all output before publication or submission.

**Custom Software Deliverables**
Unless otherwise specified in a SOW, custom software code and deliverables become the property of the client upon full payment of all invoices. Boardwalk Labs retains the right to reuse general-purpose, non-proprietary code, frameworks, and development patterns developed independently of the engagement.

**Our Platform**
The Boardwalk Labs platform, website, brand, design system, and all underlying technology remain the exclusive intellectual property of Boardwalk Labs LLC. All rights reserved.`,
  },
  {
    id: 'tos-ai', n: '06', title: 'AI-Generated Content Disclaimer',
    body: `Octopilot AI uses large language models to generate text. You acknowledge and agree that:

**Accuracy is Not Guaranteed**
AI-generated content may contain errors, inaccuracies, outdated information, or statements that appear plausible but are factually incorrect ("hallucinations"). You are solely responsible for reviewing, verifying, and editing all AI-generated output before use.

**Not Professional Advice**
Nothing produced by Octopilot AI constitutes legal, medical, financial, academic, or other professional advice. Do not rely on AI output as a substitute for qualified professional judgment.

**User Responsibility**
You assume all risk and responsibility for how you use AI-generated content. Boardwalk Labs shall not be liable for any harm arising from your reliance on AI output without independent verification.`,
  },
  {
    id: 'tos-payment', n: '07', title: 'Payment & Billing',
    body: `**Subscription Products**
Paid subscriptions to Octopilot AI are billed in advance on a monthly or annual basis. All fees are non-refundable except as required by law or as explicitly stated in our refund policy.

**Custom Software Contracts**
Payment terms for custom software engagements are specified in the applicable SOW. Standard terms are 50% upfront and 50% on delivery, unless otherwise agreed in writing. Invoices not paid within 30 days of the due date are subject to a late fee of 1.5% per month.

**Taxes**
You are responsible for all applicable taxes associated with your use of our services. We will collect sales tax where required by law.

**Disputes**
If you believe a charge is in error, contact us at support@octopilotai.com within 30 days of the charge. We will investigate and respond within 10 business days.`,
  },
  {
    id: 'tos-disclaimers', n: '08', title: 'Disclaimers',
    body: `THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.

WE DO NOT WARRANT THAT THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS. WE DO NOT WARRANT THE ACCURACY, COMPLETENESS, OR RELIABILITY OF ANY CONTENT GENERATED BY OUR AI SYSTEMS.

Some jurisdictions do not allow the exclusion of implied warranties, so the above exclusions may not apply to you.`,
  },
  {
    id: 'tos-liability', n: '09', title: 'Limitation of Liability',
    body: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, BOARDWALK LABS LLC AND ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF OUR SERVICES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

OUR TOTAL LIABILITY TO YOU FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR OUR SERVICES SHALL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO US IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR (B) ONE HUNDRED DOLLARS ($100).

THESE LIMITATIONS APPLY REGARDLESS OF THE THEORY OF LIABILITY (CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE).`,
  },
  {
    id: 'tos-governing', n: '10', title: 'Governing Law & Disputes',
    body: `**Governing Law**
These Terms are governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of law provisions.

**Dispute Resolution**
We strongly prefer to resolve disputes through direct communication. If you have a concern, please contact us first at support@octopilotai.com. We will make a good-faith effort to resolve the issue within 30 days.

If we cannot resolve a dispute through direct communication, any legal action or proceeding shall be brought exclusively in the state or federal courts located in Albany County, New York. You consent to personal jurisdiction in those courts.

**No Class Actions**
You agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated, or representative action.

**Contact**
Boardwalk Labs LLC
No. 418 Broadway, Suite N
Albany, New York 12207
support@octopilotai.com

These Terms were last updated on ${UPDATED}.`,
  },
];

// ─── Compliance badges ───────────────────────────────────────────
const badges = [
  { label: 'FERPA', desc: 'Student education records handled per federal law' },
  { label: 'COPPA', desc: 'No data collection from children under 13' },
  { label: 'GDPR', desc: 'EU data subject rights honored and supported' },
  { label: 'CCPA', desc: 'California Consumer Privacy Act compliant' },
  { label: 'AES-256', desc: 'All data encrypted at rest' },
  { label: 'TLS 1.2+', desc: 'All data encrypted in transit' },
];

// ─── Sidebar TOC ─────────────────────────────────────────────────
function Sidebar({ sections, active }) {
  return (
    <div style={{
      position: 'sticky', top: 120, width: 220,
      flexShrink: 0, fontFamily: F.mono,
    }}>
      {sections.map((s) => (
        <a key={s.id} href={`#${s.id}`} style={{
          display: 'block', padding: '8px 0',
          borderLeft: `2px solid ${active === s.id ? C.accent : C.line}`,
          paddingLeft: 16, marginBottom: 2,
          fontFamily: F.mono, fontSize: 11, letterSpacing: '0.1em',
          color: active === s.id ? C.ink : C.mute,
          textDecoration: 'none',
          transition: 'color .2s, border-color .2s',
        }}>
          {s.n} — {s.title.toUpperCase()}
        </a>
      ))}
    </div>
  );
}

// ─── Single legal section ────────────────────────────────────────
function LegalSection({ section }) {
  return (
    <div id={section.id} style={{ marginBottom: 96, scrollMarginTop: 120 }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: 20, marginBottom: 32 }}>
        <div style={{
          fontFamily: F.display, fontSize: 64, fontWeight: 300,
          fontStyle: 'italic', color: C.accent, lineHeight: 1, flexShrink: 0,
        }}>
          {section.n}
        </div>
        <h2 style={{
          fontFamily: F.display, fontSize: 36, fontWeight: 400,
          margin: 0, letterSpacing: '-0.02em', color: C.ink, lineHeight: 1.1,
        }}>
          {section.title}
        </h2>
      </div>
      <div style={{ borderTop: `1px solid ${C.line}`, paddingTop: 32 }}>
        {section.body.split('\n\n').map((para, i) => {
          if (para.startsWith('**') && para.includes('**\n') === false && para.endsWith('**')) {
            return null;
          }
          const parts = para.split(/(\*\*[^*]+\*\*)/g);
          return (
            <p key={i} style={{
              fontFamily: para.startsWith('—') ? F.mono : F.sans,
              fontSize: para.startsWith('—') ? 13 : 16,
              lineHeight: 1.7,
              color: C.mute,
              margin: '0 0 20px',
              letterSpacing: para.startsWith('—') ? '0.05em' : 0,
              paddingLeft: para.startsWith('—') ? 16 : 0,
              borderLeft: para.startsWith('—') ? `2px solid ${C.line}` : 'none',
            }}>
              {parts.map((part, j) => {
                if (part.startsWith('**') && part.endsWith('**')) {
                  return (
                    <span key={j} style={{ fontFamily: F.display, fontSize: 18, fontWeight: 500, color: C.ink, display: 'block', marginBottom: 8, letterSpacing: '-0.01em' }}>
                      {part.slice(2, -2)}
                    </span>
                  );
                }
                return part;
              })}
            </p>
          );
        })}
      </div>
    </div>
  );
}

// ─── Main page ───────────────────────────────────────────────────
export default function TrustCenter() {
  const [tab, setTab] = useState('privacy');
  const [active, setActive] = useState('');
  const sections = tab === 'privacy' ? privacy : terms;

  // Track active section via IntersectionObserver
  useEffect(() => {
    const ids = sections.map(s => s.id);
    const observers = ids.map(id => {
      const el = document.getElementById(id);
      if (!el) return null;
      const obs = new IntersectionObserver(
        ([e]) => { if (e.isIntersecting) setActive(id); },
        { rootMargin: '-20% 0px -70% 0px' }
      );
      obs.observe(el);
      return obs;
    });
    return () => observers.forEach(o => o?.disconnect());
  }, [tab, sections]);

  // Scroll to top on tab switch
  useEffect(() => { window.scrollTo({ top: 0, behavior: 'smooth' }); }, [tab]);

  return (
    <div style={{ background: C.bg, minHeight: '100vh' }}>

      {/* ── Nav ── */}
      <div style={{
        position: 'fixed', top: 0, left: 0, right: 0, zIndex: 50,
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        padding: '20px 48px',
        background: 'rgba(243,238,228,0.92)', backdropFilter: 'blur(12px)',
        borderBottom: `1px solid ${C.line}`,
      }}>
        <Link to="/" style={{ display: 'flex', alignItems: 'center', gap: 12, textDecoration: 'none', color: C.ink }}>
          <svg width="28" height="28" viewBox="0 0 28 28">
            <rect x="2" y="2" width="24" height="24" fill="none" stroke={C.ink} strokeWidth="1.5" />
            <rect x="8" y="8" width="12" height="12" fill={C.accent} />
          </svg>
          <span style={{ fontFamily: F.display, fontSize: 18, fontWeight: 500 }}>Boardwalk Labs</span>
        </Link>
        <div style={{ fontFamily: F.mono, fontSize: 11, color: C.mute, letterSpacing: '0.2em' }}>
          TRUST CENTER
        </div>
        <Link to="/" style={{
          fontFamily: F.sans, fontSize: 13, color: C.ink, textDecoration: 'none',
          display: 'flex', alignItems: 'center', gap: 6,
        }}>
          ← Back to site
        </Link>
      </div>

      {/* ── Hero ── */}
      <div style={{
        background: C.deep, color: C.bg, padding: '160px 48px 120px',
        position: 'relative', overflow: 'hidden',
      }}>
        <div style={{
          position: 'absolute', inset: 0,
          background: 'radial-gradient(ellipse at 20% 60%, rgba(227,36,0,0.18) 0%, transparent 55%)',
        }} />
        <div style={{ position: 'relative', maxWidth: 900 }}>
          <div style={{ fontFamily: F.mono, fontSize: 11, color: C.gold, letterSpacing: '0.25em', marginBottom: 32 }}>
            BOARDWALK LABS · LEGAL & PRIVACY
          </div>
          <h1 style={{
            fontFamily: F.display, fontSize: 'clamp(64px, 9vw, 140px)',
            fontWeight: 300, margin: '0 0 40px', lineHeight: 0.88,
            letterSpacing: '-0.045em',
          }}>
            Trust by design,<br />
            not <em style={{ color: C.accent }}>policy</em>.
          </h1>
          <p style={{ fontFamily: F.sans, fontSize: 18, lineHeight: 1.6, color: 'rgba(243,238,228,0.65)', maxWidth: 600, margin: 0 }}>
            We built our products for educators, researchers, and clients who need to trust the tools they use. This page tells you exactly what we do with your data — in plain language.
          </p>
          <div style={{ marginTop: 48, fontFamily: F.mono, fontSize: 11, color: 'rgba(243,238,228,0.35)', letterSpacing: '0.15em' }}>
            LAST UPDATED {UPDATED.toUpperCase()}
          </div>
        </div>
      </div>

      {/* ── Compliance badges ── */}
      <div style={{ background: C.bgDeep, padding: '64px 48px', borderBottom: `1px solid ${C.lineStrong}` }}>
        <div style={{ fontFamily: F.mono, fontSize: 11, color: C.mute, letterSpacing: '0.2em', marginBottom: 32 }}>
          COMPLIANCE & STANDARDS
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 2 }}>
          {badges.map((b) => (
            <div key={b.label} style={{
              background: C.bg, padding: '28px 24px',
              borderTop: `3px solid ${C.accent}`,
            }}>
              <div style={{ fontFamily: F.display, fontSize: 28, fontWeight: 500, letterSpacing: '-0.02em', color: C.ink, marginBottom: 8 }}>
                {b.label}
              </div>
              <div style={{ fontFamily: F.sans, fontSize: 12, color: C.mute, lineHeight: 1.45 }}>
                {b.desc}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ── Tab switcher ── */}
      <div style={{
        position: 'sticky', top: 65, zIndex: 40,
        background: 'rgba(243,238,228,0.95)', backdropFilter: 'blur(8px)',
        borderBottom: `1px solid ${C.line}`,
        display: 'flex', gap: 0, padding: '0 48px',
      }}>
        {[['privacy', 'Privacy Policy'], ['terms', 'Terms of Service']].map(([key, label]) => (
          <button key={key} onClick={() => setTab(key)} style={{
            background: 'none', border: 'none', padding: '20px 0',
            marginRight: 48, fontFamily: F.sans, fontSize: 13, fontWeight: 500,
            color: tab === key ? C.ink : C.mute,
            borderBottom: `2px solid ${tab === key ? C.accent : 'transparent'}`,
            letterSpacing: '0.02em', transition: 'all .2s',
          }}>
            {label}
          </button>
        ))}
      </div>

      {/* ── Document body ── */}
      <div style={{ padding: '80px 48px 160px', display: 'flex', gap: 80, maxWidth: 1200, margin: '0 auto' }}>
        <Sidebar sections={sections} active={active} />
        <div style={{ flex: 1 }}>
          {sections.map((s) => <LegalSection key={s.id} section={s} />)}
        </div>
      </div>

      {/* ── Footer strip ── */}
      <div style={{
        background: C.deep, color: 'rgba(243,238,228,0.5)',
        padding: '32px 48px', fontFamily: F.mono, fontSize: 11,
        letterSpacing: '0.1em', display: 'flex', justifyContent: 'space-between',
      }}>
        <span>© 2026 BOARDWALK LABS LLC · ALBANY, NEW YORK</span>
        <a href="mailto:support@octopilotai.com" style={{ color: C.gold, textDecoration: 'none' }}>
          LEGAL QUESTIONS → support@octopilotai.com
        </a>
      </div>

    </div>
  );
}
